first_app/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name='first_app'
urlpatterns=[
    url(r'^$',views.index,name='index'),
    url(r'^registeruser/',views.usercreate,name='userform'),
    url(r'^bookEnter/',views.bookEnter,name='bookEnter'),
    url(r'^electronicEnter/',views.electronicEnter,name='electronicEnter'),
    url(r'^sportEnter/',views.sportEnter,name='sportEnter'),
    url(r'^storeEnter/', views.StoreEnter, name='storeEnter'),
    url(r'^profile/(?P<pk>[a-zA-z-._0-9]+)/',views.profile,name="Profile"),
    url('^basic/',views.basic,name="basic"),
    url(r'^bookview/$',views.BookListView.as_view(),name="BookView"),
    url(r'^electronicview/$',views.ElectronicListView.as_view(),name="ElectronicView"),
    url(r'^sportview/$',views.SportListView.as_view(),name="SportView"),
    url(r'^bookview/(?P<pk>\d+)/$',views.BookDetail,name='BookDetail'),
    url(r'^Electronicview/(?P<pk>\d+)/$',views.ElectronicDetail.as_view(),name='ElectronicDetail'),
    url(r'^Sportview/(?P<pk>\d+)/$',views.SportDetail.as_view(),name='SportDetail'),
    url(r'^bookbuy/(?P<pk>\d+)/$',views.BookBuy.as_view(),name='BookBuy'),
    url(r'^book_buy_confirmed/(?P<pk>\d+)/$',views.bookBuyConfirmed,name='BookBuyConfirmed'),
    url(r'^Electronic_buy_confirmed/(?P<pk>\d+)/$',views.ElectronicBuyConfirmed,name='ElectronicBuyConfirmed'),
    url(r'^sportbuy/(?P<pk>\d+)/$',views.SportsBuyConfirmed,name='SportsBuyConfirmed'),
    url(r'^login/$',auth_views.LoginView.as_view(template_name='first_app/login.html'),name="login"),
    url(r'^logout/$',auth_views.LogoutView.as_view(template_name='first_app/logout.html'),name="logout"),
]

stock_management/urls.py
from django.contrib import admin
from django.urls import path
from first_app import urls
from django.conf.urls import include,url
from first_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^first_app/',include('first_app.urls')),

]

first_app/forms.py
from django import forms
from first_app.models import User1,Books,Stores,Electronics,Sports
from django.contrib.auth.models import User
class RegisterUserForm(forms.ModelForm):
    class Meta():
        model=User1
        fields=('f_name','m_name','l_name','Hostel_Type','Block','Email_Id','DOB')

class Loginform(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User
        fields=('username','password')

class BookEnterForm(forms.ModelForm):
    class Meta():
        model=Books
        fields='Book_Id,Course_Id,Book_Name,Book_Price,Publisher,Edition,Descrition'.split(',')


class ElectronicEnterForm(forms.ModelForm):
    class Meta():
        model=Electronics
        fields='product_id,product_name,product_price,product_brand,product_models,description_text,garantee'.split(',')

class SportEnterForm(forms.ModelForm):
    class Meta():
        model=Sports
        fields='item_name,item_price,descrition_text'.split(',')

class Storeform(forms.ModelForm):
    class Meta():
        model=Stores
        fields='__all__'

first_app/views.py
from django.shortcuts import render,redirect
from . import models
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from first_app.forms import RegisterUserForm,Loginform,BookEnterForm,Storeform,ElectronicEnterForm,SportEnterForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from  django.contrib import messages

# Create your views here.

def usercreate(request):
    form=RegisterUserForm()
    form1=Loginform()
    if request.method=='POST':
        form=RegisterUserForm(request.POST)
        form1=Loginform(request.POST)
    if (form.is_valid() and form1.is_valid()):
        user=form1.save()
        user.set_password(user.password)
        user.save()
        obj=models.User1()
        login_id12 = form1.cleaned_data['username']
        messages.success(request,f'Account created for {login_id12}')
        obj.login_id=User.objects.filter(username=login_id12)[0]
        obj.f_name=form.cleaned_data['f_name']
        obj.m_name = form.cleaned_data['m_name']
        obj.l_name=form.cleaned_data['l_name']
        obj.Hostel_Type=form.cleaned_data['Hostel_Type']
        obj.Block=form.cleaned_data['Block']
        obj.Email_Id=form.cleaned_data['Email_Id']
        obj.DOB=form.cleaned_data['DOB']
        obj.save()
        return index(request)
    else:
        print("Error")
    return render(request,'first_app/register.html',{'form':form,'form1':form1})





def StoreEnter(request):
    form=Storeform()
    if request.method=='POST':
        form=Storeform(request.POST)
    if (form.is_valid()):
        form.save(commit=True)
    return render(request,'first_app/storeEnter.html',{"form":form})

def basic(request):
    return render(request,'first_app/basic.html')

def index(request):
    return render(request,'first_app/index.html')

class BookListView(ListView):
    model=models.Books

    def get_queryset(self,*args,**kargs):
        qs=super(BookListView,self).get_queryset(*args,**kargs)
        qs=qs.filter(sold=False)
        # print("1 Yes")
        return qs

class BookDetail(DetailView):
    model=models.Books



class BookBuy(DetailView):
    template_name = 'first_app/book_buy.html'
    model=models.Books

@login_required
def bookBuyConfirmed(request,pk):
    temp=models.Books.objects.filter(Book_Id=pk)[0]
    temp.sold=True
    print(temp.user_id)
    user_id=models.User.objects.filter(username=temp.user_id)[0]
    user = models.User1.objects.filter(login_id=user_id.id)[0]
    # print(user)
    param={'book_name':temp.Book_Name,'book_descrition':temp.Descrition,'book_price':temp.Book_Price,'book_edition':temp.Edition,'book_publication':temp.Publisher,'user_name':user.f_name,'user_middle_name':user.m_name,'user_last_name':user.l_name,'user_Hostel_Type':user.Hostel_Type,'user_Block':user.Block,"user_Email_ID":user.Email_Id}
    temp.save()
    basket=models.Shopping_Basket()
    basket.user_id=user_id
    basket.books=temp
    basket.save()
    return render(request,'first_app/book_buy.html',param)
#
# def user_login(request,next):
#     print("Come")
#     if request.method=="POST":
#         username=request.POST.get('username')
#         password=request.POST.get('password')
#         user=authenticate(username=username,password=password)
#         print("Authicate")
#         if user:
#             if user.is_active:
#                 login(request,user)
#                 print("Yes")
#                 return HttpResponseRedirect('/first_app'+'/'+next)
#             else:
#                 print("Not found")
#         else:
#             return HttpResponseRedirect('/first_app/login')
#     else:
#         return render(request,'first_app/login.html')

@login_required
def bookEnter(request):
    form=BookEnterForm()
    if request.method=='POST':
        form=BookEnterForm(request.POST)
    if (form.is_valid()):
        # form.save()
        # Book_Name = form.cleaned_data['Book_Name']
        # obj=models.Books.objects.filter(Book_Name=Book_Name)[0]
        obj=models.Books()
        obj.Course_Id=form.cleaned_data['Course_Id']
        obj.Book_Name=form.cleaned_data['Book_Name']
        obj.Book_Price=form.cleaned_data['Book_Price']
        obj.Publisher=form.cleaned_data['Publisher']
        obj.Edition=form.cleaned_data['Edition']
        obj.Descrition=form.cleaned_data['Descrition']
        obj.user_id=request.user
        # obj.store_id = 'No store'
        obj.save()
        # obj.sold=False
        # obj.of_shop=False
        # obj.quantity=1

        # print(obj.Course_Id)
        # print(User.is_authenticated,User.is_active,User.first_name,request.user)
        return redirect('/first_app/bookview')
    return render(request,'first_app/bookEnter.html',{"form":form,'title':"Books"})

@login_required
def sportEnter(request):
    # print("I  m in electronic enter")
    # print("I  m in electronic enter")
    form=SportEnterForm()
    # print(form)
    if request.method=='POST':
        form=SportEnterForm(request.POST)
    if (form.is_valid()):
        # form.save()
        # Book_Name = form.cleaned_data['Book_Name']
        # obj=models.Books.objects.filter(Book_Name=Book_Name)[0]
        obj=models.Sports()
        # obj.=form.cleaned_data['garantee']
        obj.item_name=form.cleaned_data['item_name']
        obj.item_price=form.cleaned_data['item_price']
        obj.descrition_text=form.cleaned_data['descrition_text']
        # obj.product_models=form.cleaned_data['product_models']
        # obj.description_text=form.cleaned_data['description_text']
        obj.user_id=request.user
        # obj.store_id = 'No store'
        obj.save()
        # obj.sold=False
        # obj.of_shop=False
        # obj.quantity=1

        # print(obj.Course_Id)
        # print(User.is_authenticated,User.is_active,User.first_name,request.user)
        return redirect('/first_app/sportview')


    return render(request,'first_app/bookEnter.html',{"form":form,'title':"Sports Item"})


@login_required
def electronicEnter(request):
    # print("I  m in electronic enter")
    # print("I  m in electronic enter")
    form=ElectronicEnterForm()
    # print(form)
    if request.method=='POST':
        form=ElectronicEnterForm(request.POST)
    if (form.is_valid()):
        # form.save()
        # Book_Name = form.cleaned_data['Book_Name']
        # obj=models.Books.objects.filter(Book_Name=Book_Name)[0]
        obj=models.Electronics()
        obj.garantee=form.cleaned_data['garantee']
        obj.product_Name=form.cleaned_data['product_name']
        obj.product_price=form.cleaned_data['product_price']
        obj.product_brand=form.cleaned_data['product_brand']
        obj.product_models=form.cleaned_data['product_models']
        obj.description_text=form.cleaned_data['description_text']
        obj.user_id=request.user
        # obj.store_id = 'No store'
        obj.save()
        # obj.sold=False
        # obj.of_shop=False
        # obj.quantity=1

        # print(obj.Course_Id)
        # print(User.is_authenticated,User.is_active,User.first_name,request.user)
        return redirect('/first_app/Electronicview')


    return render(request,'first_app/bookEnter.html',{"form":form,'title':"Electronic"})

@login_required
def profile(request,pk):
    user_id = models.User.objects.filter(username=pk)[0]
    user = models.User1.objects.filter(login_id=user_id.id)[0]
    booksold=models.Shopping_Basket.objects.filter(user_id=user_id.id)
    x=[]
    for i in booksold:
        book=models.Books.objects.filter(Book_Name=i.books)[0]
        user1=models.User1.objects.filter(login_id=i.user_id)[0]
        dic={'book':book.Book_Name,'user_name':user1.Email_Id,'dop':i.date_of_purchase}
        print(user1.Email_Id)
        x.append(dic)
    return render(request, 'first_app/profile.html', {'f_name':user.f_name,'m_name':user.m_name,'l_name':user.l_name,'Hostel_Type':user.Hostel_Type,'Block':user.Block,'Email_Id':user.Email_Id,'DOB':user.DOB,'age':user.age,"x": x})



class ElectronicListView(ListView):
    model=models.Electronics

    def get_queryset(self,*args,**kargs):
        qs=super(ElectronicListView,self).get_queryset(*args,**kargs)
        qs=qs.filter(sold=False)
        print("1 Yes")
        return qs

class SportListView(ListView):
    model=models.Sports
    def get_queryset(self,*args,**kargs):
        qs=super(SportListView,self).get_queryset(*args,**kargs)
        qs=qs.filter(sold=False)
        print("1 Yes")
        return qs


class ElectronicDetail(DetailView):
    model=models.Books

class SportDetail(DetailView):
    model=models.Books


@login_required
def ElectronicBuyConfirmed(request,pk):
    temp=models.Electronics.objects.filter(product_id=pk)[0]
    temp.sold=True
    print(temp.user_id)
    user_id=models.User.objects.filter(username=temp.user_id)[0]
    user = models.User1.objects.filter(login_id=user_id.id)[0]
    # print(user)
    param={'product_name':temp.product_name,'descrition':temp.description_text,'product_price':temp.product_price,'product_brand':temp.product_brand,'product_models':temp.product_models,'garantee':temp.garantee,'user_name':user.f_name,'user_middle_name':user.m_name,'user_last_name':user.l_name,'user_Hostel_Type':user.Hostel_Type,'user_Block':user.Block,"user_Email_ID":user.Email_Id}
    temp.save()
    basket=models.Shopping_Basket()
    basket.user_id=user_id
    basket.electories_items=temp
    basket.save()
    return render(request,'first_app/electronic_buy.html',param)


@login_required
def SportsBuyConfirmed(request,pk):
    temp=models.Sports.objects.filter(product_id=pk)[0]
    temp.sold=True
    # print(temp.user_id)
    user_id=models.User.objects.filter(username=temp.user_id)[0]
    user = models.User1.objects.filter(login_id=user_id.id)[0]
    # print(user)

templates/first_app/bookEnter.html
<!doctype html>
{% extends 'first_app/basic.html'%}
    {%block title%}Add Books{% endblock %}
    {%block css%}{% endblock %}
{% block body %}
<div class="mx-auto" style="width: 800px;">
<div class="w-75 p-3 form-row justify-content-center jumbotron">


<form method="POST">{% csrf_token %}
    <h1>{{title}}</h1>
    <br>
    {{ form.as_p }}
    <button type="submit" class="btn btn-outline-success" value="submit">Submit</button>
</form>
</div>
</div>
{% endblock %}

</body>
</html>

templates/first_app/book_buy.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
    <link rel="stylesheet" href="{% static 'first_app/css/book_buy.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">
</head>
<body>
<div class="box">
<h1>Book Buy</h1>
<h3>Confirmed !!!</h3>
Book Name:
{{book_name}}
<br>
Description:
{{book_descrition}}
<br>
Price: ₹
{{book_price}}
<br>
Edition:
{{book_edition}}
<br>
Publication:
{{book_publication}}
<br>
<br>
<h2>Seller Details:</h2>
Name:
{{user_name}}
{{user_middle_name}}
{{user_last_name}}
<br>
Hostel:
{{user_Hostel_Type}}
<br>
Block:
{{user_Block}}
<br>
Email:
{{user_Email_ID}}
<br>
</div>
<!-- <button><a href="/first_app/book_buy_confirmed/{{object.Book_Id}}">Buy Confirmed</a></button> -->
</body>
</html>

templates/first_app/books_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
    <link rel="stylesheet" href="{% static 'first_app/css/book_buy.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">
</head>
<body>
<div class="box">
<h1>Details:</h1>
Book Name:
{{book_name}}
<br>
Description:
{{book_descrition}}
<br>
Price: ₹
{{book_price}}
<br>
Edition:
{{book_edition}}
<br>
Publication:
{{book_publication}}
<br>
<br>
<h2>Seller Details:</h2>
Name:
{{user_name}}
{{user_middle_name}}
{{user_last_name}}
<br>
Hostel:
{{user_Hostel_Type}}
<br>
Block:
{{user_Block}}
<br>
Email:
{{user_Email_ID}}
<br>
</div>
<!-- <button><a href="/first_app/book_buy_confirmed/{{object.Book_Id}}">Buy Confirmed</a></button> -->
</body>
</html>

templates/first_app/books_list.html
<!doctype HTML>
{% extends 'first_app/basic.html'%}
{% load static %}
    {%block title%}Books{% endblock %}
    {%block css%}
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
        <link rel="stylesheet" href="{% static 'first_app/css/books_list.css'%}">
    {% endblock %}
{% block body %}

<!-- <div>
    {{ obj.Book_Name }}
    {{  obj.Book_Price }}
    {{ obj.Descrition }}
    <a><button>Buy</button></a>
    <a href="/first_app/bookview/{{obj.Book_Id}}"><button>View</button></a>
</div> -->
<section class="section-tours" id="section-tours">
    <div class="row">
        {% for obj in object_list %}

        <div class="col-1-of-4">
            <div class="card">
                <div class="card__side card__side--front">
                    <div class="card__picture card__picture--1">
                            &nbsp;
                    </div>
                    <h4 class="card__heading">
                        <span class="card__heading-span card__heading-span--1">{{ obj.Book_Name }}</span>
                    </h4>
                </div>
                <div class="card__side card__side--back card__side--back-1">
                    <div class="card__cta">
                        <div class="card__price-box">
                            <p class="card__price-only">{{ obj.Descrition }} {{ obj.count }}</p>
                            <a href="/first_app/bookview/{{obj.Book_Id}}" class="btnsmall">Full Description</a>
                            <p class="card__price-value">₹<br>{{ obj.Book_Price }} </p>
                        </div>
                        <a href="/first_app/book_buy_confirmed/{{obj.Book_Id}}" class="btn btn--white">Buy</a>
                    </div>
                </div>
            </div>
        </div>
            {% if obj.count == 3 %}
                <div>
                    {{ obj.count }}
                </div>
                </div>
                <div class="row">
            {% endif %}
    {% endfor %}
    </div>
</section>


{% endblock %}

</html>

templates/first_app/electronicEnter.html
<!doctype html>
{% extends 'first_app/basic.html'%}
    {%block title%}Add Books{% endblock %}
    {%block css%}{% endblock %}
{% block body %}
<div class="mx-auto" style="width: 800px;">
<div class="w-75 p-3 form-row justify-content-center jumbotron">
<form method="POST">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-outline-success" value="submit">Submit</button>
</form>
</div>
</div>
{% endblock %}

</body>
</html>

templates/first_app/electronics_list.html
<!doctype HTML>
{% extends 'first_app/basic.html'%}
{% load static %}
    {%block title%}Books{% endblock %}
    {%block css%}
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
        <link rel="stylesheet" href="{% static 'first_app/css/books_list.css'%}">
    {% endblock %}
{% block body %}

<!-- <div>
    {{ obj.Book_Name }}
    {{  obj.Book_Price }}
    {{ obj.Descrition }}
    <a><button>Buy</button></a>
    <a href="/first_app/bookview/{{obj.Book_Id}}"><button>View</button></a>
</div> -->
<section class="section-tours" id="section-tours">
    <div class="row">
        {% for obj in object_list %}

        <div class="col-1-of-4">
            <div class="card">
                <div class="card__side card__side--front">
                    <div class="card__picture card__picture--1">
                            &nbsp;
                    </div>
                    <h4 class="card__heading">
                        <span class="card__heading-span card__heading-span--1">{{ obj.product_brand }}</span>
                    </h4>
                </div>
                <div class="card__side card__side--back card__side--back-1">
                    <div class="card__cta">
                        <div class="card__price-box">
                            <p class="card__price-only">{{ obj.product_models }} {{ obj.count }}</p>
                            <a href="/first_app/Electronicview/{{obj.product_id}}" class="btnsmall">Full Description</a>
                            <p class="card__price-value">₹<br>{{ obj.product_price }} </p>
                        </div>
                        <a href="/first_app/Electronic_buy_confirmed/{{obj.product_id}}" class="btn btn--white">Buy</a>
                    </div>
                </div>
            </div>
        </div>
            {% if obj.count == 3 %}
                <div>
                    {{ obj.count }}
                </div>
                </div>
                <div class="row">
            {% endif %}
    {% endfor %}
    </div>
</section>


{% endblock %}

</html>

templates/first_app/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'first_app/css/login.css'%}">
</head>
<body>
<form  class="box" method="POST">{% csrf_token %}
    <h1>LOGIN</h1>
    <!-- Username -->
    <input type="text" name="username" placeholder="Username">
    <!-- Password -->
    <input type="password" name="password" placeholder="Password">
    <input type="submit" value="LOGIN" class="btn btn-white">
</form>
</body>
</html>

templates/first_app/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>
You are logged out
<a href="{% url 'first_app:index' %}">Go back</a>

</body>
</html>

templates/first_app/profile.html
{% extends 'first_app/basic.html'%}
{% load static %}

    {%block title%}Add Books{% endblock %}
    {%block css%}
        <link rel="stylesheet" href="{% static 'first_app/css/profile.css'%}">
    {% endblock %}
{% block body %}
    <h2>Profile:</h2>
    <br>
    <div class="box">
    Name:
    {{f_name}}
    {{m_name}}
    {{l_name}}
    <br>
    Hostel Type:
    {{Hostel_Type}}
    <br>
    Block:
    {{Block}}
    <br>
    Email:
    {{Email_Id}}
    <br>
    DOB:
    {{DOB}}
    <br>
    Age:
    {{age}}
    </div>
    <br><br><br>
    <h3>Products Sold:</h3>
    <br>
    <div>
        <table class="table table-dark">
            <thead>
                <th scope="col">Product Name</th>
                <th scope="col">Sold to</th>
                <th scope="col">Sold on</th>
            </thead>
            {% for i in x %}
            <tr>
                <td>{{ i.book }}</td>
                <td>{{ i.user_name}}</td>
                <td>{{ i.dop }}</td>
            </tr>
            {% endfor%}
        </table>
        <br><br><br>
    </div>
    <!-- {% for i in x %}
        {{ i.book }}   {{ i.user}}
    <br>
    {% endfor %} -->

    {% endblock %}

</body>
</html>

templates/first_app/register.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<div class="mx-auto" style="width: 800px;">
<div class="w-75 p-3 form-row justify-content-center jumbotron">
        <h3>Register Now !!!</h3><hr><br><br><br>
<div class="form-group">
<form method="POST">{% csrf_token %}
    {{ form.as_p }}
    {{ form1.as_p }}
    <br>
    <input type="submit" value="Submit" class="btn btn-outline-primary">
</div>
</div>
</div>
</form>
</body>
</html>

templates/first_app/sport_buy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
<h1>Sports Buy Confirmed</h1>
<h1>Sports</h1>
{{item_name}}
<br>
{{descrition_text}}
<br>
{{item_price}}
<br>
<h1>Users</h1>
<br>
{{user_name}}
<br>
{{user_middle_name}}
<br>
{{user_last_name}}
<br>
{{user_Hostel_Type}}
<br>
{{user_Block}}
<br>
{{user_Email_ID}}
<br>
</body>
<a href="/first_app/">Home page</a>
</html>

templates/first_app/sports_list.html
<!doctype HTML>
{% extends 'first_app/basic.html'%}
{% load static %}
    {%block title%}Books{% endblock %}
    {%block css%}
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
        <link rel="stylesheet" href="{% static 'first_app/css/books_list.css'%}">
    {% endblock %}
{% block body %}

<!-- <div>
    {{ obj.Book_Name }}
    {{  obj.Book_Price }}
    {{ obj.Descrition }}
    <a><button>Buy</button></a>
    <a href="/first_app/bookview/{{obj.Book_Id}}"><button>View</button></a>
</div> -->
<section class="section-tours" id="section-tours">
    <div class="row">
        {% for obj in object_list %}

        <div class="col-1-of-4">
            <div class="card">
                <div class="card__side card__side--front">
                    <div class="card__picture card__picture--1">
                            &nbsp;
                    </div>
                    <h4 class="card__heading">
                        <span class="card__heading-span card__heading-span--1">{{ obj.item_name }}</span>
                    </h4>
                </div>
                <div class="card__side card__side--back card__side--back-1">
                    <div class="card__cta">
                        <div class="card__price-box">
                            <p class="card__price-only">{{ obj.descrition_text }} {{ obj.count }}</p>
                            <a href="/first_app/sportview/{{obj.item_id}}" class="btnsmall">Full Description</a>
                            <p class="card__price-value">₹<br>{{ obj.item_price }} </p>
                        </div>
                        <a href="/first_app/sportbuy/{{obj.item_id}}" class="btn btn--white">Buy</a>
                    </div>
                </div>
            </div>
        </div>
            {% if obj.count == 3 %}
                <div>
                    {{ obj.count }}
                </div>
                </div>
                <div class="row">
            {% endif %}
    {% endfor %}
    </div>
</section>


{% endblock %}

</html>

templates/first_app/storeEnter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register</title>
</head>
<body>
<form method="POST">{% csrf_token %}
    {{ form.as_p }}
    {{ form1.as_p }}
    <input type="submit" value="submit">
</form>
</body>
</html>

templates/first_app/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>T</title>
</head>
<body>
<h1>This is for test</h1>
{{  tr  }}
{{ Book_Name }}

</body>
</html>